main/urls.py
from django.urls import path
from .views import home, ParkingSpaceListView, ReservationListView, ParkingSpaceCreateView, ParkingSpaceUpdateView, \
                    delete_parking, ReservationCreateView, ReservationUpdateView, delete_reservation
from .api_urls import urlpatterns as api_urlpatterns

urlpatterns = [
    path('', home, name='home'),
    path('parking-lots', ParkingSpaceListView.as_view(), name='parking_spaces'),
    path('create-parking', ParkingSpaceCreateView.as_view(), name='create_parking'),
    path('update-parking/<int:id>/', ParkingSpaceUpdateView.as_view(), name='update_parking'),
    path('delete-parking/<int:id>/', delete_parking, name='delete_parking'),
    path('reservation', ReservationListView.as_view(), name='reservation'),
    path('create-reservation', ReservationCreateView.as_view(), name='create_reservation'),
    path('update-reservation/<int:id>/', ReservationUpdateView.as_view(), name='update_reservation'),
    path('delete-reservation/<int:id>/', delete_reservation, name='delete_reservation'),
] + api_urlpatterns

parking_lot/urls.py
from django.contrib import admin
from django.urls import path, include
from .swagger import swagger_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('users/', include(('user.urls', 'user'), namespace='users')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + swagger_urlpatterns

user/urls.py
from django.urls import path
from .views import register, CustomUserLoginView, logout_view
from .api_urls import urlpatterns as api_urlpatterns

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', CustomUserLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
] + api_urlpatterns

main/models.py
from django.db import models
from user.models import CustomUser


class ParkingSpace(models.Model):
    is_reserved = models.BooleanField(default=False)
    created_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Reserved' if self.is_reserved else 'Not reserved'


class Reservation(models.Model):
    reserved_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    parking_space = models.ForeignKey(ParkingSpace, on_delete=models.CASCADE)
    duration = models.CharField(max_length=50)

main/forms.py
from django import forms
from .models import ParkingSpace, Reservation


class ParkingSpaceForm(forms.ModelForm):

    class Meta:
        model = ParkingSpace
        fields = ['created_by', 'is_reserved']

        widgets = {
            'created_by': forms.Select(attrs={
                'diabled': True
            }),
            'is_reserved': forms.CheckboxInput(attrs={
                'style': "float: left"
            })
        }

        labels = {
            'is_reserved': "Is empty?"
        }

        labels = {
            'created_by': "Lot creator",
            'is_reserved': "Is not reserved?",
        }


class ReservationForm(forms.ModelForm):

    class Meta:
        model = Reservation
        fields = ['duration', 'parking_space']

        widgets = {
            'duration': forms.TextInput(),
            'parking_space': forms.Select()
        }

        labels = {
            'parking_space': "Lot number",
            'duration': "Duration of reservation"
        }

main/views.py
import datetime
from linecache import cache

from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import ParkingSpace, Reservation
from .forms import ParkingSpaceForm, ReservationForm
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from user.models import CustomUser


def home(request):
    return render(request, 'main/home.html', context={})


class ParkingSpaceListView(ListView, PermissionRequiredMixin):
    login_url = '/users/login/'
    model = ParkingSpace.objects.all()
    template_name = 'main/parkings.html'
    # permission_required = ''
    raise_exception = True

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm(self.permission_required):
            raise PermissionDenied()
        return super(ParkingSpaceListView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        query = self.model

        context = {
            'object_list': query,

        }
        return render(request, self.template_name, context)


class ParkingSpaceCreateView(CreateView):
    model = ParkingSpace.objects.all()
    template_name = 'main/create_parking.html'
    login_url = '/users/login/'
    form_class = ParkingSpaceForm
    # permission_required = 'organizations.add_authorganization'
    # raise_exception = True

    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.has_perm(self.permission_required):
    #         raise PermissionDenied()
    #     return super(ParkingSpaceCreatView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        form.fields['created_by'].queryset = CustomUser.objects.filter(id=request.user.id)
        context = {
            'form': form,
            'object': self.model
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect('main:parking_spaces')

        form = self.form_class(data=request.POST)
        context = {
            'form': form
        }

        return render(request, self.template_name, context)


class ParkingSpaceUpdateView(UpdateView):
    model = ParkingSpace.objects.all()
    template_name = 'main/update_parking.html'
    login_url = '/users/login/'
    form_class = ParkingSpaceForm
    # permission_required = 'organizations.add_authorganization'
    # raise_exception = True

    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.has_perm(self.permission_required):
    #         raise PermissionDenied()
    #     return super(ParkingSpaceCreatView, self).dispatch(request, *args, **kwargs)

    def get(self, request, id=None, *args, **kwargs):
        form = self.form_class(instance=ParkingSpace.objects.get(id=id))
        print(ParkingSpace.objects.get(id=id))
        context = {
            'form': form,
            'object': self.model,
            'id': id
        }
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        form = self.form_class(instance=ParkingSpace.objects.get(id=id), data=request.POST)
        print(request.POST)
        if form.is_valid():
            print(True)
            form.save()
            cache.clear()
            return redirect('main:parking_spaces')

        form = self.form_class(instance=ParkingSpace.objects.get(id=id))
        context = {
            'form': form
        }

        return render(request, self.template_name, context)


def delete_parking(request, id):
    query = get_object_or_404(ParkingSpace, id=id)
    if request.method == 'POST':
        query.delete()
        cache.clear()
        return redirect('main:parking_spaces')
    context = {'object': query, 'id': id}
    return render(request, 'main/delete_parking.html', context)


class ReservationListView(ListView, PermissionRequiredMixin):
    login_url = '/users/login/'
    model = Reservation.objects.all()
    template_name = 'main/reservation.html'
    # permission_required = ''
    raise_exception = True

    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm(self.permission_required):
            raise PermissionDenied()
        return super(ReservationListView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        query = self.model

        context = {
            'object_list': query,

        }
        return render(request, self.template_name, context)


class ReservationCreateView(CreateView):
    model = Reservation.objects.all()
    template_name = 'main/create_reservation.html'
    login_url = '/users/login/'
    form_class = ReservationForm
    # permission_required = 'organizations.add_authorganization'
    # raise_exception = True

    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.has_perm(self.permission_required):
    #         raise PermissionDenied()
    #     return super(ParkingSpaceCreatView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        form.fields['reserved_by'] = CustomUser.objects.get(id=request.user.id)
        form.fields['parking_space'].queryset = ParkingSpace.objects.filter(is_reserved=False).values_list('id', flat=True)
        context = {
            'form': form,
            'object': self.model
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        update_data = request.POST.copy()
        update_data.update({'reserved_by_id': request.user.id})
        form = self.form_class(data=update_data)
        if form.is_valid():
            data = form.save(commit=False)
            data.reserved_by_id = request.user.id

            data.save()
            return redirect('main:reservation')

        form = self.form_class(data=request.POST)
        context = {
            'form': form
        }

        return render(request, self.template_name, context)


class ReservationUpdateView(UpdateView):
    model = Reservation.objects.all()
    template_name = 'main/update_reservation.html'
    login_url = '/users/login/'
    form_class = ReservationForm
    # permission_required = 'organizations.add_authorganization'
    # raise_exception = True

    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.has_perm(self.permission_required):
    #         raise PermissionDenied()
    #     return super(ParkingSpaceCreatView, self).dispatch(request, *args, **kwargs)

    def get(self, request, id=None, *args, **kwargs):
        form = self.form_class(instance=Reservation.objects.get(id=id))
        form.fields['parking_space'].queryset = ParkingSpace.objects.filter(is_reserved=False).values_list('id',
                                                                                                           flat=True)
        context = {
            'form': form,
            'object': self.model,
            'id': id
        }
        return render(request, self.template_name, context)

    def post(self, request, id=None, *args, **kwargs):
        form = self.form_class(instance=Reservation.objects.get(id=id), data=request.POST)
        if form.is_valid():
            form.save()
            cache.clear()
            return redirect('main:reservation')

        form = self.form_class(instance=Reservation.objects.get(id=id))
        context = {
            'form': form
        }

        return render(request, self.template_name, context)


def delete_reservation(request, id):
    query = get_object_or_404(Reservation, id=id)
    if request.method == 'POST':
        query.delete()
        cache.clear()
        return redirect('main:reservation')
    context = {'object': query, 'id': id}
    return render(request, 'main/delete_reservation.html', context)

templates/main/create_parking.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.rtl.css' %}">#}

    {# fontawesome icons #}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/regular.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/solid.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.esm.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
<div class="container my-5">
    <div class="row my-5">
        <div class="col-6 offset-3">
            <form action="{% url 'main:create_parking' %}" method="POST">
                {% csrf_token %}
                <div class="">
                    {{ form.created_by | as_crispy_field }}
                </div>
                <div>
                    {{ form.is_reserved | as_crispy_field }}
                </div>
                <button class="btn btn-lg btn-success" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>

</body>
</html>

templates/main/create_reservation.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.rtl.css' %}">#}

    {# fontawesome icons #}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/regular.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/solid.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.esm.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
<div class="container my-5">
    <div class="row my-5">
        <div class="col-6 offset-3">
            <form action="{% url 'main:create_reservation' %}" method="POST">
                {% csrf_token %}
                <div class="my-2">
                    {{ form.parking_space | as_crispy_field }}
                </div>
                <div class="my-2">
                    {{ form.duration | as_crispy_field }}
                </div>
                <button class="btn btn-primary mt-3" type="submit">Create</button>
            </form>
        </div>
    </div>
</div>

</body>
</html>

templates/main/delete_parking.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.rtl.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.rtl.css' %}">#}

    {# fontawesome icons #}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/regular.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/solid.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.esm.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
<div class="container my-5">
    <div class="row my-5">
        <div class="col-6 offset-3">
            <form action="{% url 'main:delete_parking' id %}" method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <input class="btn btn-danger" type="submit" value="Confirm">
            </form>
        </div>
    </div>
</div>
</body>
</html>

templates/main/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.rtl.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.rtl.css' %}">#}

    {# fontawesome icons #}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/regular.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/solid.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.esm.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
<div class="container">
    <div class="row align-items-center">
        <div class="col-2 left">
            <h1>HOME</h1>
        </div>
        <div class="col">
            <a class="link link-danger text-decoration-none float-end mx-4" href="{% url 'users:logout' %}">Logout</a>
            <a class="link link-success text-decoration-none float-end" href="{% url 'users:login' %}">Login</a>
        </div>
    </div>
    <div class="row">
        <div class="col"><a class="link link-info text-decoration-none" href="{% url 'main:parking_spaces' %}">Parking Spaces List</a></div>
        <div class="col"><a class="link link-primary text-decoration-none" href="{% url 'main:reservation' %}">Reservation</a></div>
        <div class="col"><a class="link link-danger text-decoration-none" href="/swagger/">API Documentation</a></div>
    </div>
</div>
</body>
</html>

templates/main/parkings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parking Lots</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">

    {# fontawesome icons #}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/regular.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/solid.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.esm.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>

<div class="container my-5">
    <div class="row my-5">
        <h2 class="text-info">Parking Lots List</h2>
        <table class="table table-bordered">
            <thead  class="bg-light">
            <tr>
                <td>ID</td>
                <td>Condition</td>
                <td>Action</td>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{ object.id }}</td>
                <td>
                    {% if object.is_reserved %}
                    Reserved
                    {% else %}
                    Empty
                    {% endif %}
                </td>
                <td>
                    <a class="link link-primary text-decoration-none" href="{% url 'main:update_parking' object.id %}">Update</a>
                    <a class="link link-danger text-decoration-none" href="{% url 'main:delete_parking' object.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <a class="btn btn-primary mt-2" style="width: 80px" href="{% url 'main:create_parking' %}">Add</a>
    </div>
</div>

</body>
</html>

templates/main/reservation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">

    {# fontawesome icons #}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/regular.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/solid.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.esm.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
 <div class="container mt-5">
    <div class="row mt-5">
        <h3>Parking Lot Reservation List</h3>
        <table class="table table-bordered">
            <thead class="bg-light">
            <tr>
                <td>ID</td>
                <td>Owner</td>
                <td>Lot number</td>
                <td>Duration</td>
                <td colspan="2">Action</td>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{ object.id }}</td>
                <td>{{ object.reserved_by }}</td>
                <td>
                    {{ object.parking_space.id }}
                </td>
                <td>{{ object.duration }}</td>
                <td>
                    <a class="link link-primary text-decoration-none" href="{% url 'main:update_reservation' object.id %}">Update</a>
                    <a class="link link-danger text-decoration-none" href="{% url 'main:delete_reservation' object.id %}">Delete</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <a class="btn btn-primary mt-2" style="width: 80px" href="{% url 'main:create_reservation' %}">Add</a>
    </div>
    </div>
</body>
</html>