main/urls.py
from django.urls import path
from .views import home, ParkingSpaceListView, ReservationListView, ParkingSpaceCreateView, ParkingSpaceUpdateView, \
                    delete_parking, ReservationCreateView, ReservationUpdateView, delete_reservation
from .api_urls import urlpatterns as api_urlpatterns

urlpatterns = [
    path('', home, name='home'),
    path('parking-lots', ParkingSpaceListView.as_view(), name='parking_spaces'),
    path('create-parking', ParkingSpaceCreateView.as_view(), name='create_parking'),
    path('update-parking/<int:id>/', ParkingSpaceUpdateView.as_view(), name='update_parking'),
    path('delete-parking/<int:id>/', delete_parking, name='delete_parking'),
    path('reservation', ReservationListView.as_view(), name='reservation'),
    path('create-reservation', ReservationCreateView.as_view(), name='create_reservation'),
    path('update-reservation/<int:id>/', ReservationUpdateView.as_view(), name='update_reservation'),
    path('delete-reservation/<int:id>/', delete_reservation, name='delete_reservation'),
] + api_urlpatterns

parking_lot/urls.py
from django.contrib import admin
from django.urls import path, include
from .swagger import swagger_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('users/', include(('user.urls', 'user'), namespace='users')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + swagger_urlpatterns

user/urls.py
from django.urls import path
from .views import register, CustomUserLoginView, logout_view
from .api_urls import urlpatterns as api_urlpatterns

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', CustomUserLoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
] + api_urlpatterns

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'username'

    ROLE_CHOIECES = [
        ('Manager', 'Manager'),
        ('Employee', 'Employee')
    ]

    role = models.CharField(max_length=15, choices=ROLE_CHOIECES)

    objects = CustomUserManager()

    def __str__(self):
        return self.username

user/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm, forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("username", 'email', 'password1', 'password2')

        labels = {
            'username': 'Username',
            'email': 'Email',
            'password1': 'Password',
            'password2': 'Password confirmation',
        }

    def username_clean(self):
        username = self.cleaned_data['username'].lower()
        new = self.model.objects.filter(username=username)
        if new.count():
            raise ValidationError("User Already Exist")
        return username

    def email_clean(self):
        email = self.cleaned_data['email'].lower()
        new = self.model.objects.filter(email=email)
        if new.count():
            raise ValidationError(" Email Already Exist")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")
        return password2


class CustomUserLoginForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ['username', 'password']

user/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from .serializers import MyTokenObtainPairSerializer, RegisterSerializer, CustomUserSerializer
from .models import CustomUser as User
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.views import TokenObtainPairView
from django.http import Http404
from rest_framework.response import Response
from rest_framework import status


def register(request):
    form = CustomUserCreationForm()
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:home')

    context = {
        'forms': form
    }
    return render(request, 'user/register.html', context)


class CustomUserLoginView(LoginView):
    template_name = 'user/login.html'
    success_url = reverse_lazy("main:home")


def logout_view(request):
    logout(request)
    return redirect('users:login')


class MyObtainTokenPairView(TokenObtainPairView):
    permission_classes = (AllowAny,)
    serializer_class = MyTokenObtainPairSerializer


class CustomUserAPIView(ModelViewSet):

    """User API CRUD"""

    queryset = User.objects.all()
    serializer_class = CustomUserSerializer

    def get_types(self, pk=None):
        try:
            return User.objects.get(pk=pk)
        except User.DoesNotExist:
            raise Http404

    def list(self, request, *args, **kwargs):
        serializer = self.serializer_class(self.queryset, many=True)
        return Response(serializer.data)

    def create(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def retrieve(self, request, pk=None, *args, **kwargs):
        query = self.get_types(pk)
        serializer = self.serializer_class(query)
        return Response(serializer.data)

    def update(self, request, pk=None, *args, **kwargs):
        query = self.get_types(pk)
        serializer = self.serializer_class(query, data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def destroy(self, request, pk=None, *args, **kwargs):
        query = self.get_types(pk)
        query.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

templates/user/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.rtl.css' %}">#}

    {# fontawesome icons #}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/regular.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/solid.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.esm.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <div class="container" style="margin-top: 10%">
        <div class="row">
            <div class="col-6 offset-3">
                <h1 class="mx-auto text-center">Login</h1>
                <div class="card bg-light">
                    <form class="w-75 mx-auto my-5" action="{% url 'user:login' %}" method="POST">
                        {% csrf_token %}
                        <div class="my-3">
                            {{ form.username | as_crispy_field }}
                        </div>
                        <div class="my-3">
                            {{ form.password | as_crispy_field }}
                        </div>
                        <div class="row">
                            <button class="btn btn-lg btn-success mt-3 mx-auto w-25" type="submit">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/user/register.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">#}
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.rtl.css' %}">#}
    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap-utilities.rtl.css' %}">#}

    {# fontawesome icons #}
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/brands.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/regular.css' %}">
    <link rel="stylesheet" href="{% static 'fontawesome/css/solid.css' %}">

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap.esm.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
</head>
<body>
<div class="container" style="margin-top: 7%">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center">Registration</h1>
            <div class="card bg-light m-5 p-5">
                <form action="{% url 'user:register' %}" method="POST">
                    {% csrf_token %}
                    {% for form in forms %}
                        {{ form | as_crispy_field }}
                    {% endfor %}
                    <div class="row">
                        <button class="btn btn-lg btn-success mx-auto w-25 mt-3">Sign up</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
</html>